DELIMITER //
CREATE PROCEDURE  admUpDateClientes (IN  NM_CATEGORIA  VARCHAR(100), IN  ATUALIZACAO_ID  VARCHAR(10), IN  ATUALIZACAO_DESCRICAO  VARCHAR(100), IN  ATUALIZACAO_SCRIPT  VARCHAR(2000))
	LANGUAGE SQL
	NOT DETERMINISTIC
	CONTAINS SQL
	SQL SECURITY DEFINER
	COMMENT ''
BEGIN
	INSERT INTO admCategorias (codCategoria, codRelacao, Categoria,Ordem, Descricao01)
	
	SELECT 
		(IF(IsNull(NOVO_CONTROLE), 1, NOVO_CONTROLE)) AS controle
		,(SELECT admCategorias.codCategoria FROM admCategorias Where Categoria = NM_CATEGORIA and codRelacao = 0) AS idRelacao
		,UCase(ATUALIZACAO_DESCRICAO)
		,ATUALIZACAO_ID		
		,ATUALIZACAO_SCRIPT
	FROM 
		admSubNumeroDeCategoriaNovo;


END //

DELIMITER ;